### ISSUE TITLE
Easier-to-use audio generation

### ISSUE THREAD

**Issue by zmbc** [kantord/LibreLingo#1473]
**Is your feature request related to a problem? Please describe.**
If I want to add a new course with TTS listening exercises, it is not easy to do so.

**Describe the solution you'd like**
I am not sure about all the details, but it would at least include:
- Configuration of TTS in the course YAML file.
- A script that recognizes missing audios, generates them using the course's TTS configuration, and places them in the right directory with the right names.

**Describe alternatives you've considered**
I've seen [this](https://github.com/kantord/LibreLingo/blob/main/docs/creating_a_python_language_learning_app_using_librelingo_courses.md) but it's more of an example for developers than anything, and in any case it doesn't show the whole process.

The fetchAudios.sh script is in bash, which is probably not ideal and even less ideal if it gets more complex. I'm guessing Python would be better. There is also no documentation I can find of how the audios_to_fetch.csv file is generated.

**Additional context**
I'm interested in implementing this, if it gets the go-ahead. If it's not too much to review, I think this and allowing other audio sources could be combined into one MR.

**Comment by kantord** [comment]
@zmbc see also:

- https://github.com/kantord/LibreLingo/issues/1464
- https://github.com/kantord/LibreLingo/issues/714

those are possible alternatives to using TTS.

Of course I will also accept your suggested contribution 😉 How do you plan to implement it?

**Comment by zmbc** [comment]
@kantord Thanks, that's helpful.

Here's my initial idea of how this would work.

*course.yaml*
```yaml
...
Settings:
  Audio:
    Enabled: True
    TTS:
      # Enabled: False can be used if audio should only be present on words/phrases with recordings
      Enabled: True # Default: True
      Provider: Polly # Default: Polly, can be used in future if other TTS providers are available
      Voice: Aditi # No default
      Engine: standard # Can be standard or neural, default: standard
```

*skill.yaml*
```yaml
New words:
  # This word will feed the `Word` field into the course's TTS engine
  - Word: soweli
    Translation: dog
    Images:
      - dog1
      - dog2
      - dog3
  # This word will pronounce a custom IPA string using the course's TTS engine (while still displaying the word as written, of course)
  - Word: soweli
    IPA: "'soweli"
    Translation: cat
    Images:
      - cat1
      - cat2
      - cat3
  # This word will use a recording from a third party
  - Word: soweli
    Audio source: Tatoeba # Default: TTS
    Audio source ID: 6717361 # No default, this is a Tatoeba ID number (or ID number in other system as they are added)
    Translation: cat
    Images:
      - cat1
      - cat2
      - cat3
  # This word will use a local recording made specifically for LibreLingo
  - Word: soweli
    Audio source: Custom
    Translation: cat
    Images:
      - cat1
      - cat2
      - cat3
# Phrases have the same options as words
...
```

The [voice directory](https://github.com/kantord/LibreLingo/tree/main/apps/web/static/voice) would be given subdirectories -- first one for each language, and then within each language split by source, like so:

```
voice/
  es/
    tts/
      LongHashedIdFileNames.mp3
    custom/
      SameLongHashedIdFileNames.mp3
    third-party/
      tatoeba/
        SameLongHashedIdFileNames.mp3
  toki-pona/
    ... {the same}
```

And then the last but most important part, the script. I'm picturing a replacement for [fetchAudios](https://github.com/kantord/LibreLingo/blob/main/apps/web/scripts/fetchAudios.sh), written in Python, which makes all the above happen -- verify that there are corresponding files for `Custom` audios, download audio from third parties, and generate audio using TTS.

It would have two modes:
* In overwrite mode, it would do all of that from scratch, deleting previously existing versions.
* In update mode, it would only do the above for audios that don't already exist.

I am not sure whether it will be possible/good to make it a standalone script -- if not, it could be a function in a Python package, called via a CLI with a top-level bash script for convenience like `librelingo_json_export`. Perhaps it could live in the `librelingo_audios` package? I don't know what that package is for, exactly, so maybe it's not a good fit.

**Comment by kantord** [comment]
```yaml
Settings:
  Audio:
    Enabled: True
    TTS:
      # Enabled: False can be used if audio should only be present on words/phrases with recordings
      Enabled: True # Default: True
      Provider: Polly # Default: Polly, can be used in future if other TTS providers are available
      Voice: Aditi # No default
      Engine: standard # Can be standard or neural, default: standard
```

I am thinking, maybe it would be a good idea to allow multiple TTS settings at the same time? So that a random pick can be used to generate each audio, thus allowing multiple voice actors in the same course.
