### ISSUE TITLE
Translation in "new words" overwrites mini-dictionary

### ISSUE THREAD

**Issue by zmbc** [kantord/LibreLingo#1715]
**Describe the bug**
When a word has a `Translation` in the `New words` array, no matter what you put in the `Mini-dictionary`, only the `New words` value will appear in the hint tooltip.

**To Reproduce**

skill yaml (excerpt)

```yaml
New words:
  - Word: toki!
    Translation: Hello!
    Images:
      - hello1
      - hello2
      - hello3
...
Phrases:
  - Phrase: toki
    Translation: communicate
...
Mini-dictionary:
  toki pona:
    - toki:
      - communicate
      - hello
```

The resulting mini-dictionary entry is:

```json
{
  "word": "toki",
  "definition": "Hello!"
}
```

**Expected behavior**
The resulting mini-dictionary entry should be:

```json
{
  "word": "toki",
  "definition": "Hello!\ncommunicate\nhello"
}
```

**Additional context**
First reported in #1445, but I thought it should have its own issue for tracking.
