### ISSUE TITLE
blank page and "Uncaught (in promise) TypeError: pictures is null" in browser console

### ISSUE THREAD

**Issue by szabgab** [kantord/LibreLingo#1817]
Given a course with the only skill like this generates a blank page (when clicking on "practice Animals") and an error "Uncaught (in promise) TypeError: pictures is null" in the console of the browser. 
http://localhost:3000/course/xyz/skill/animals  (the name of the project was xyx)

It seems every "Word" in the "New words" must have at least one Image.

**IMHO having an associated images should not be a requirement.**

If we reload the page in the browser we get a 500 error:
```
Cannot read property 'map' of null

TypeError: Cannot read property 'map' of null
    at eval (webpack:///./src/components/ChallengeScreen.svelte?:77:83)
    at Array.map (<anonymous>)
    at eval (webpack:///./src/components/ChallengeScreen.svelte?:77:52)
    at Object.$$render (webpack:///./node_modules/svelte/internal/index.mjs?:1855:22)
    at eval (webpack:///./src/routes/course/%5BcourseName%5D/skill/./src/routes/course/%5BcourseName%5D/skill/%5Bid%5D/index.svelte/index.svelte?:57:173)
    at Object.$$render (webpack:///./node_modules/svelte/internal/index.mjs?:1855:22)
    at Object.default (webpack:///./src/node_modules/@sapper/internal/App.svelte?:39:190)
    at eval (webpack:///./src/routes/_layout.svelte?:64:129)
    at Object.$$render (webpack:///./node_modules/svelte/internal/index.mjs?:1855:22)
    at eval (webpack:///./src/node_modules/@sapper/internal/App.svelte?:36:151)
```

Skill without images:

```
Skill:
  Name: Animals
  Id: 2
  Thumbnails:
    - dog1
    - lion3
    - cat3

New words:
  - Word: perro
    Translation: dog

Phrases:
  - Phrase: Max es un perro
    Translation: Max is a dog

Mini-dictionary:
  Ladino:
    - un: a/an (masc.)
    - es: is
    - Max: Max (name)


  English:
    - a:
      - un
      - una
    - Max: Max (name)
    - is: es
```

The same skill with images works:

```
Skill:
  Name: Animals
  Id: 2
  Thumbnails:
    - dog1
    - lion3
    - cat3

New words:
  - Word: perro
    Translation: dog
    Images:
      - dog1
      - dog2
      - dog3


Phrases:
  - Phrase: Max es un perro
    Translation: Max is a dog

Mini-dictionary:
  Ladino:
    - un: a/an (masc.)
    - es: is
    - Max: Max (name)


  English:
    - a:
      - un
      - una
    - Max: Max (name)
    - is: es
```
