### ISSUE TITLE
Add ability to link to online dictionaries

### ISSUE THREAD

**Issue by Skivling** [kantord/LibreLingo#3380]
Creating a course, I want to link to a relevant online dictionary so the learner can get proper definitions of the words.

This could be shown in the UI if there is ever a dictionary page where a learner can look through the words in the course. 

I want this feature for my LL-based application, will be adding it on top anyway but it's nice to have support in LibreLingo normally.

**Comment by kantord** [comment]
what about allowing courses to have a resources.md file that is similar to the explanation .md files for each skill, but it is on the course level :thinking:

**Comment by Skivling** [comment]
The point is to be able to put these links in an in-app dictionary so the LibreLingo course doesn't have to provide dictionary-level definitions for words. For my course, Te Reo Māori, the de-facto dictionary is https://maoridictionary.co.nz and for learners to be able to be looking through an in-app dictionary which shows the words they've learned, where they're included in sentences in the course etc, then be able to click through to an online dictionary entry for it to get the full understanding of the definition would be great.

For example:
```yaml
New words:
  - Word: tahi
    Translation: one
    Also accepted: 1
    Dictionary Link: https://maoridictionary.co.nz/word/7059
    Images:
      - one1
      - one2
      - one3
```

If it was a markdown file how would that be read by applications?

On another note, it would be nice to be able to link to other resources for the learner, because just a LibreLingo course is never going to be able to cover nuances, culture, etc; and for these to be displayed in a nice way in the UI.
