### ISSUE TITLE
Support motivation words in new language

### ISSUE THREAD

**Issue by Skivling** [kantord/LibreLingo#3383]
There should be support for a course file which defines all the motivation and question words in the new language, to provide more immersion.
This is like:
- Great job!
- Translate this sentence:
etc. 
All the small words in the UI could be shown prominently in the new language, with the source language lighter beside it.

I'm adding this to my LibreLingo-based mobile app, and would like to see it supported upstream.

**Comment by kantord** [comment]
Good idea! I suppose this could be part of the metadata file of courses. How would you implement this?

**Comment by Skivling** [comment]
It could be in `course.yaml`, although that would get big really quickly. I was thinking it would be a separate file, `motivation-words.yaml` or something that is clear what it is.
It would probably be indexed by the English translations for them, and structured something like this:
  ```yaml
  Motivation Words:
     Te Reo Māori: # Target language, the one we want to show more prominently
          Well Done:
          Awesome: Tau ke!
          New Word: Kupu Hou
          Translate this sentence:
          Correct:
          Not quite.:
          Try Again!:
          You got this!:
          Mistakes are how we learn.:
          Check:
          Continue:
          Loading...:
          Match the translations:
          It was a typo:
     English: # If the source language was different from english this would be another section
  ```
  
This is the list I had though of so far. And I would hope that any of these fields could become a list, so that the application can show either or.
