### ISSUE TITLE
[Feature Request] Skill (and module?) Subtitles

### ISSUE THREAD

**Issue by Skivling** [kantord/LibreLingo#3387]
It would be great to be able to have a title, e.g. Numbers, then have a subtitle underneath it, with either showing a couple of the words taught or something else, e.g. 'Count from 0 to 99'.

Currently it just shows a couple of the words, which is OK but it would be better to have a course developer defined subtitle.

Example implementation:
```yaml
Skill:
  Id: d46f999d-3145-4c1f-8487-6466b0445f46
  Name: Numbers
  Subtitle: Count from 0 to 99 # here
  Thumbnails:
    - one3
    - two3
    - three1
```
