### ISSUE TITLE
Skill types

### ISSUE THREAD

**Issue by Skivling** [kantord/LibreLingo#3403]
I have been thinking about the approach I will take when organising skills to be taught to the learner in my app and I think it would be great to have an identifier for Skills.

Skills will remain being loosely defined and able to include any number of Words, Phrases or Characters (#1143). That flexibility is important to be able to adapt to any teacher's needs.

However:
- It would be nice to have separated vocabulary lists disconnected from the main skills.
- It would be nice to separate Character skills (when those are implemented - which I may do sometime)
- I would like to have a separate section in my app for teaching extended vocabulary lists.

I propose:
- Skills can have an optional parameter which suggests what kind of skill they are. 
    - `mixed` is the default and can includes any amount of Words, Phrases or Characters.
    - `vocabulary` (or `vocab`?) specifically includes a list of vocabulary Words and no Phrases or Characters. These can be created according to specific themes, such as 'Common Jobs' 
    - `character` specifically if the course includes a whole new script and it is useful to separate them from mixed skills.
    - `phrase` - I can't see a use case for this, there isn't much distinction between a `phrase` type and a `mixed` type that only has Phrases; but it would be good to support it in case it is useful sometime. 
    - `conversation` for #3388 when that is implemented.

#### Examples

Not everyone wants to learn the names of specific things, but it's good to be able to have vocabulary lists not required to learn, but available. 
```yaml
Skill:
  Id: c6e16576-76cb-4507-a86c-db416e43fd3c
  Name: Fruit and Vegetables
  Type: vocabulary
  Thumbnails:
  ...
```

For someone learning a foreign alphabet such as Ukranian/Russian, these skills could be separated from the main skills so the learner can do them at their own pace.
```yaml
Skill:
  Id: de2dcfac-f2ac-413f-b6ef-3315a456d3d7
  Name: А, Б, В, Г, а, б, в, г 
  Type: character
  Thumbnails:
  ...
```
